[package]
name = "Reveaal"
version = "0.1.0"
build = "src/build.rs"
authors = ["Peter Greve <Pgreve16@student.aau.dk>"]
edition = "2018"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
clap = { git = "https://github.com/clap-rs/clap/", features=["yaml"] }
boolean_expression = "0.3.10"
pest = "2.1.3"
pest_derive = "2.1.0"
regex = "1.3.5"
eval = "0.4.3"
rand = "0.7.3"
rand_chacha = "0.2.2"
empty-box = "0.1.1"
pkg-config = {git = "https://github.com/rust-lang/pkg-config-rs.git"}

[build-dependencies]
bindgen = "0.54.0"
cc = "1.0.56"
