name: Build Artifacts

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
  workflow_dispatch:

jobs:   
  macos:
    name: Build MacOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - uses: arduino/setup-protoc@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
    - run: cargo build --release
    - uses: actions/upload-artifact@v2
      with:
        name: reveaal-macos
        path: target/release/Reveaal
        if-no-files-found: error
  
  win:
    name: Build Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - uses: arduino/setup-protoc@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
    - run: cargo build --release
    - uses: actions/upload-artifact@v2
      with:
        name: reveaal-windows
        path: target/release/Reveaal.exe
        if-no-files-found: error

  ubuntu:
    name: Build Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - uses: arduino/setup-protoc@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
    - run: cargo build --release
    - uses: actions/upload-artifact@v2
      with:
        name: reveaal-ubuntu
        path: target/release/Reveaal
        if-no-files-found: error
